(progn
  (set (quote i) (cons 1 2))
  (print "the value of i is:")
  (print i)
  (terpri)
  (print "the car of i is: ")
  (print (car i))
  (terpri)
  (print "the cdr of i is: ")
  (print (cdr i))
  (terpri)
  (rcar! i 3)
  (rcdr! i 4)
  (print "now the value of i is: ")
  (print i)
  (terpri))
